/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ImprimirRouteImport } from './routes/imprimir'
import { Route as CheckinOnlineRouteImport } from './routes/checkin-online'
import { Route as CadastroEmpresaRouteImport } from './routes/cadastro-empresa'
import { Route as AvaliarRouteImport } from './routes/avaliar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedVendasProdutosRouteImport } from './routes/_authenticated/vendas-produtos'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AuthenticatedTarifarioRouteImport } from './routes/_authenticated/tarifario'
import { Route as AuthenticatedReservasRouteImport } from './routes/_authenticated/reservas'
import { Route as AuthenticatedRelatorioConsumoAguaRouteImport } from './routes/_authenticated/relatorio-consumo-agua'
import { Route as AuthenticatedReclamacoesRouteImport } from './routes/_authenticated/reclamacoes'
import { Route as AuthenticatedQrcodesRouteImport } from './routes/_authenticated/qrcodes'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedMensagensRouteImport } from './routes/_authenticated/mensagens'
import { Route as AuthenticatedMemoriaIaRouteImport } from './routes/_authenticated/memoria-ia'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedFichasCheckinRouteImport } from './routes/_authenticated/fichas-checkin'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedEmpresaRouteImport } from './routes/_authenticated/empresa'
import { Route as AuthenticatedDespesasRouteImport } from './routes/_authenticated/despesas'
import { Route as AuthenticatedDecisoesRouteImport } from './routes/_authenticated/decisoes'
import { Route as AuthenticatedDashboardQuartosRouteImport } from './routes/_authenticated/dashboard-quartos'
import { Route as AuthenticatedDashboardEstrategicoRouteImport } from './routes/_authenticated/dashboard-estrategico'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedCentralEstrategicaRouteImport } from './routes/_authenticated/central-estrategica'
import { Route as AuthenticatedAvaliacoesRouteImport } from './routes/_authenticated/avaliacoes'
import { Route as AuthenticatedAssistenteRouteImport } from './routes/_authenticated/assistente'
import { Route as AuthenticatedAjudaSistemaRouteImport } from './routes/_authenticated/ajuda-sistema'
import { Route as AuthenticatedAdminPlataformaRouteImport } from './routes/_authenticated/admin-plataforma'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprimirRoute = ImprimirRouteImport.update({
  id: '/imprimir',
  path: '/imprimir',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinOnlineRoute = CheckinOnlineRouteImport.update({
  id: '/checkin-online',
  path: '/checkin-online',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroEmpresaRoute = CadastroEmpresaRouteImport.update({
  id: '/cadastro-empresa',
  path: '/cadastro-empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliarRoute = AvaliarRouteImport.update({
  id: '/avaliar',
  path: '/avaliar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendasProdutosRoute =
  AuthenticatedVendasProdutosRouteImport.update({
    id: '/vendas-produtos',
    path: '/vendas-produtos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTarifarioRoute = AuthenticatedTarifarioRouteImport.update({
  id: '/tarifario',
  path: '/tarifario',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReservasRoute = AuthenticatedReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatorioConsumoAguaRoute =
  AuthenticatedRelatorioConsumoAguaRouteImport.update({
    id: '/relatorio-consumo-agua',
    path: '/relatorio-consumo-agua',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReclamacoesRoute =
  AuthenticatedReclamacoesRouteImport.update({
    id: '/reclamacoes',
    path: '/reclamacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQrcodesRoute = AuthenticatedQrcodesRouteImport.update({
  id: '/qrcodes',
  path: '/qrcodes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMensagensRoute = AuthenticatedMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemoriaIaRoute = AuthenticatedMemoriaIaRouteImport.update({
  id: '/memoria-ia',
  path: '/memoria-ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFichasCheckinRoute =
  AuthenticatedFichasCheckinRouteImport.update({
    id: '/fichas-checkin',
    path: '/fichas-checkin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresaRoute = AuthenticatedEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDespesasRoute = AuthenticatedDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDecisoesRoute = AuthenticatedDecisoesRouteImport.update({
  id: '/decisoes',
  path: '/decisoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardQuartosRoute =
  AuthenticatedDashboardQuartosRouteImport.update({
    id: '/dashboard-quartos',
    path: '/dashboard-quartos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardEstrategicoRoute =
  AuthenticatedDashboardEstrategicoRouteImport.update({
    id: '/dashboard-estrategico',
    path: '/dashboard-estrategico',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCentralEstrategicaRoute =
  AuthenticatedCentralEstrategicaRouteImport.update({
    id: '/central-estrategica',
    path: '/central-estrategica',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAvaliacoesRoute = AuthenticatedAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAssistenteRoute = AuthenticatedAssistenteRouteImport.update({
  id: '/assistente',
  path: '/assistente',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAjudaSistemaRoute =
  AuthenticatedAjudaSistemaRouteImport.update({
    id: '/ajuda-sistema',
    path: '/ajuda-sistema',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPlataformaRoute =
  AuthenticatedAdminPlataformaRouteImport.update({
    id: '/admin-plataforma',
    path: '/admin-plataforma',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avaliar': typeof AvaliarRoute
  '/cadastro-empresa': typeof CadastroEmpresaRoute
  '/checkin-online': typeof CheckinOnlineRoute
  '/imprimir': typeof ImprimirRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin-plataforma': typeof AuthenticatedAdminPlataformaRoute
  '/ajuda-sistema': typeof AuthenticatedAjudaSistemaRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/central-estrategica': typeof AuthenticatedCentralEstrategicaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard-estrategico': typeof AuthenticatedDashboardEstrategicoRoute
  '/dashboard-quartos': typeof AuthenticatedDashboardQuartosRoute
  '/decisoes': typeof AuthenticatedDecisoesRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/fichas-checkin': typeof AuthenticatedFichasCheckinRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/memoria-ia': typeof AuthenticatedMemoriaIaRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/qrcodes': typeof AuthenticatedQrcodesRoute
  '/reclamacoes': typeof AuthenticatedReclamacoesRoute
  '/relatorio-consumo-agua': typeof AuthenticatedRelatorioConsumoAguaRoute
  '/reservas': typeof AuthenticatedReservasRoute
  '/tarifario': typeof AuthenticatedTarifarioRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/vendas-produtos': typeof AuthenticatedVendasProdutosRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avaliar': typeof AvaliarRoute
  '/cadastro-empresa': typeof CadastroEmpresaRoute
  '/checkin-online': typeof CheckinOnlineRoute
  '/imprimir': typeof ImprimirRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin-plataforma': typeof AuthenticatedAdminPlataformaRoute
  '/ajuda-sistema': typeof AuthenticatedAjudaSistemaRoute
  '/assistente': typeof AuthenticatedAssistenteRoute
  '/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/central-estrategica': typeof AuthenticatedCentralEstrategicaRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/dashboard-estrategico': typeof AuthenticatedDashboardEstrategicoRoute
  '/dashboard-quartos': typeof AuthenticatedDashboardQuartosRoute
  '/decisoes': typeof AuthenticatedDecisoesRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/fichas-checkin': typeof AuthenticatedFichasCheckinRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/memoria-ia': typeof AuthenticatedMemoriaIaRoute
  '/mensagens': typeof AuthenticatedMensagensRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/qrcodes': typeof AuthenticatedQrcodesRoute
  '/reclamacoes': typeof AuthenticatedReclamacoesRoute
  '/relatorio-consumo-agua': typeof AuthenticatedRelatorioConsumoAguaRoute
  '/reservas': typeof AuthenticatedReservasRoute
  '/tarifario': typeof AuthenticatedTarifarioRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/vendas-produtos': typeof AuthenticatedVendasProdutosRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/avaliar': typeof AvaliarRoute
  '/cadastro-empresa': typeof CadastroEmpresaRoute
  '/checkin-online': typeof CheckinOnlineRoute
  '/imprimir': typeof ImprimirRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin-plataforma': typeof AuthenticatedAdminPlataformaRoute
  '/_authenticated/ajuda-sistema': typeof AuthenticatedAjudaSistemaRoute
  '/_authenticated/assistente': typeof AuthenticatedAssistenteRoute
  '/_authenticated/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/_authenticated/central-estrategica': typeof AuthenticatedCentralEstrategicaRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/dashboard-estrategico': typeof AuthenticatedDashboardEstrategicoRoute
  '/_authenticated/dashboard-quartos': typeof AuthenticatedDashboardQuartosRoute
  '/_authenticated/decisoes': typeof AuthenticatedDecisoesRoute
  '/_authenticated/despesas': typeof AuthenticatedDespesasRoute
  '/_authenticated/empresa': typeof AuthenticatedEmpresaRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/fichas-checkin': typeof AuthenticatedFichasCheckinRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/memoria-ia': typeof AuthenticatedMemoriaIaRoute
  '/_authenticated/mensagens': typeof AuthenticatedMensagensRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/qrcodes': typeof AuthenticatedQrcodesRoute
  '/_authenticated/reclamacoes': typeof AuthenticatedReclamacoesRoute
  '/_authenticated/relatorio-consumo-agua': typeof AuthenticatedRelatorioConsumoAguaRoute
  '/_authenticated/reservas': typeof AuthenticatedReservasRoute
  '/_authenticated/tarifario': typeof AuthenticatedTarifarioRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/_authenticated/vendas-produtos': typeof AuthenticatedVendasProdutosRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/avaliar'
    | '/cadastro-empresa'
    | '/checkin-online'
    | '/imprimir'
    | '/sitemap.xml'
    | '/admin-plataforma'
    | '/ajuda-sistema'
    | '/assistente'
    | '/avaliacoes'
    | '/central-estrategica'
    | '/clientes'
    | '/dashboard-estrategico'
    | '/dashboard-quartos'
    | '/decisoes'
    | '/despesas'
    | '/empresa'
    | '/equipe'
    | '/fichas-checkin'
    | '/financeiro'
    | '/integracoes'
    | '/mapa'
    | '/memoria-ia'
    | '/mensagens'
    | '/painel'
    | '/qrcodes'
    | '/reclamacoes'
    | '/relatorio-consumo-agua'
    | '/reservas'
    | '/tarifario'
    | '/vendas'
    | '/vendas-produtos'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/avaliar'
    | '/cadastro-empresa'
    | '/checkin-online'
    | '/imprimir'
    | '/sitemap.xml'
    | '/admin-plataforma'
    | '/ajuda-sistema'
    | '/assistente'
    | '/avaliacoes'
    | '/central-estrategica'
    | '/clientes'
    | '/dashboard-estrategico'
    | '/dashboard-quartos'
    | '/decisoes'
    | '/despesas'
    | '/empresa'
    | '/equipe'
    | '/fichas-checkin'
    | '/financeiro'
    | '/integracoes'
    | '/mapa'
    | '/memoria-ia'
    | '/mensagens'
    | '/painel'
    | '/qrcodes'
    | '/reclamacoes'
    | '/relatorio-consumo-agua'
    | '/reservas'
    | '/tarifario'
    | '/vendas'
    | '/vendas-produtos'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/avaliar'
    | '/cadastro-empresa'
    | '/checkin-online'
    | '/imprimir'
    | '/sitemap.xml'
    | '/_authenticated/admin-plataforma'
    | '/_authenticated/ajuda-sistema'
    | '/_authenticated/assistente'
    | '/_authenticated/avaliacoes'
    | '/_authenticated/central-estrategica'
    | '/_authenticated/clientes'
    | '/_authenticated/dashboard-estrategico'
    | '/_authenticated/dashboard-quartos'
    | '/_authenticated/decisoes'
    | '/_authenticated/despesas'
    | '/_authenticated/empresa'
    | '/_authenticated/equipe'
    | '/_authenticated/fichas-checkin'
    | '/_authenticated/financeiro'
    | '/_authenticated/integracoes'
    | '/_authenticated/mapa'
    | '/_authenticated/memoria-ia'
    | '/_authenticated/mensagens'
    | '/_authenticated/painel'
    | '/_authenticated/qrcodes'
    | '/_authenticated/reclamacoes'
    | '/_authenticated/relatorio-consumo-agua'
    | '/_authenticated/reservas'
    | '/_authenticated/tarifario'
    | '/_authenticated/vendas'
    | '/_authenticated/vendas-produtos'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AvaliarRoute: typeof AvaliarRoute
  CadastroEmpresaRoute: typeof CadastroEmpresaRoute
  CheckinOnlineRoute: typeof CheckinOnlineRoute
  ImprimirRoute: typeof ImprimirRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprimir': {
      id: '/imprimir'
      path: '/imprimir'
      fullPath: '/imprimir'
      preLoaderRoute: typeof ImprimirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin-online': {
      id: '/checkin-online'
      path: '/checkin-online'
      fullPath: '/checkin-online'
      preLoaderRoute: typeof CheckinOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-empresa': {
      id: '/cadastro-empresa'
      path: '/cadastro-empresa'
      fullPath: '/cadastro-empresa'
      preLoaderRoute: typeof CadastroEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliar': {
      id: '/avaliar'
      path: '/avaliar'
      fullPath: '/avaliar'
      preLoaderRoute: typeof AvaliarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendas-produtos': {
      id: '/_authenticated/vendas-produtos'
      path: '/vendas-produtos'
      fullPath: '/vendas-produtos'
      preLoaderRoute: typeof AuthenticatedVendasProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tarifario': {
      id: '/_authenticated/tarifario'
      path: '/tarifario'
      fullPath: '/tarifario'
      preLoaderRoute: typeof AuthenticatedTarifarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservas': {
      id: '/_authenticated/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof AuthenticatedReservasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorio-consumo-agua': {
      id: '/_authenticated/relatorio-consumo-agua'
      path: '/relatorio-consumo-agua'
      fullPath: '/relatorio-consumo-agua'
      preLoaderRoute: typeof AuthenticatedRelatorioConsumoAguaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reclamacoes': {
      id: '/_authenticated/reclamacoes'
      path: '/reclamacoes'
      fullPath: '/reclamacoes'
      preLoaderRoute: typeof AuthenticatedReclamacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qrcodes': {
      id: '/_authenticated/qrcodes'
      path: '/qrcodes'
      fullPath: '/qrcodes'
      preLoaderRoute: typeof AuthenticatedQrcodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensagens': {
      id: '/_authenticated/mensagens'
      path: '/mensagens'
      fullPath: '/mensagens'
      preLoaderRoute: typeof AuthenticatedMensagensRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memoria-ia': {
      id: '/_authenticated/memoria-ia'
      path: '/memoria-ia'
      fullPath: '/memoria-ia'
      preLoaderRoute: typeof AuthenticatedMemoriaIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fichas-checkin': {
      id: '/_authenticated/fichas-checkin'
      path: '/fichas-checkin'
      fullPath: '/fichas-checkin'
      preLoaderRoute: typeof AuthenticatedFichasCheckinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa': {
      id: '/_authenticated/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AuthenticatedEmpresaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/despesas': {
      id: '/_authenticated/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AuthenticatedDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/decisoes': {
      id: '/_authenticated/decisoes'
      path: '/decisoes'
      fullPath: '/decisoes'
      preLoaderRoute: typeof AuthenticatedDecisoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard-quartos': {
      id: '/_authenticated/dashboard-quartos'
      path: '/dashboard-quartos'
      fullPath: '/dashboard-quartos'
      preLoaderRoute: typeof AuthenticatedDashboardQuartosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard-estrategico': {
      id: '/_authenticated/dashboard-estrategico'
      path: '/dashboard-estrategico'
      fullPath: '/dashboard-estrategico'
      preLoaderRoute: typeof AuthenticatedDashboardEstrategicoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/central-estrategica': {
      id: '/_authenticated/central-estrategica'
      path: '/central-estrategica'
      fullPath: '/central-estrategica'
      preLoaderRoute: typeof AuthenticatedCentralEstrategicaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avaliacoes': {
      id: '/_authenticated/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AuthenticatedAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/assistente': {
      id: '/_authenticated/assistente'
      path: '/assistente'
      fullPath: '/assistente'
      preLoaderRoute: typeof AuthenticatedAssistenteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajuda-sistema': {
      id: '/_authenticated/ajuda-sistema'
      path: '/ajuda-sistema'
      fullPath: '/ajuda-sistema'
      preLoaderRoute: typeof AuthenticatedAjudaSistemaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-plataforma': {
      id: '/_authenticated/admin-plataforma'
      path: '/admin-plataforma'
      fullPath: '/admin-plataforma'
      preLoaderRoute: typeof AuthenticatedAdminPlataformaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminPlataformaRoute: typeof AuthenticatedAdminPlataformaRoute
  AuthenticatedAjudaSistemaRoute: typeof AuthenticatedAjudaSistemaRoute
  AuthenticatedAssistenteRoute: typeof AuthenticatedAssistenteRoute
  AuthenticatedAvaliacoesRoute: typeof AuthenticatedAvaliacoesRoute
  AuthenticatedCentralEstrategicaRoute: typeof AuthenticatedCentralEstrategicaRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedDashboardEstrategicoRoute: typeof AuthenticatedDashboardEstrategicoRoute
  AuthenticatedDashboardQuartosRoute: typeof AuthenticatedDashboardQuartosRoute
  AuthenticatedDecisoesRoute: typeof AuthenticatedDecisoesRoute
  AuthenticatedDespesasRoute: typeof AuthenticatedDespesasRoute
  AuthenticatedEmpresaRoute: typeof AuthenticatedEmpresaRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFichasCheckinRoute: typeof AuthenticatedFichasCheckinRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedMemoriaIaRoute: typeof AuthenticatedMemoriaIaRoute
  AuthenticatedMensagensRoute: typeof AuthenticatedMensagensRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedQrcodesRoute: typeof AuthenticatedQrcodesRoute
  AuthenticatedReclamacoesRoute: typeof AuthenticatedReclamacoesRoute
  AuthenticatedRelatorioConsumoAguaRoute: typeof AuthenticatedRelatorioConsumoAguaRoute
  AuthenticatedReservasRoute: typeof AuthenticatedReservasRoute
  AuthenticatedTarifarioRoute: typeof AuthenticatedTarifarioRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedVendasProdutosRoute: typeof AuthenticatedVendasProdutosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminPlataformaRoute: AuthenticatedAdminPlataformaRoute,
  AuthenticatedAjudaSistemaRoute: AuthenticatedAjudaSistemaRoute,
  AuthenticatedAssistenteRoute: AuthenticatedAssistenteRoute,
  AuthenticatedAvaliacoesRoute: AuthenticatedAvaliacoesRoute,
  AuthenticatedCentralEstrategicaRoute: AuthenticatedCentralEstrategicaRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedDashboardEstrategicoRoute:
    AuthenticatedDashboardEstrategicoRoute,
  AuthenticatedDashboardQuartosRoute: AuthenticatedDashboardQuartosRoute,
  AuthenticatedDecisoesRoute: AuthenticatedDecisoesRoute,
  AuthenticatedDespesasRoute: AuthenticatedDespesasRoute,
  AuthenticatedEmpresaRoute: AuthenticatedEmpresaRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFichasCheckinRoute: AuthenticatedFichasCheckinRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedMemoriaIaRoute: AuthenticatedMemoriaIaRoute,
  AuthenticatedMensagensRoute: AuthenticatedMensagensRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedQrcodesRoute: AuthenticatedQrcodesRoute,
  AuthenticatedReclamacoesRoute: AuthenticatedReclamacoesRoute,
  AuthenticatedRelatorioConsumoAguaRoute:
    AuthenticatedRelatorioConsumoAguaRoute,
  AuthenticatedReservasRoute: AuthenticatedReservasRoute,
  AuthenticatedTarifarioRoute: AuthenticatedTarifarioRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedVendasProdutosRoute: AuthenticatedVendasProdutosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AvaliarRoute: AvaliarRoute,
  CadastroEmpresaRoute: CadastroEmpresaRoute,
  CheckinOnlineRoute: CheckinOnlineRoute,
  ImprimirRoute: ImprimirRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
