/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ImprimirRouteImport } from './routes/imprimir'
import { Route as CadastroEmpresaRouteImport } from './routes/cadastro-empresa'
import { Route as AvaliarRouteImport } from './routes/avaliar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AuthenticatedReservasRouteImport } from './routes/_authenticated/reservas'
import { Route as AuthenticatedReclamacoesRouteImport } from './routes/_authenticated/reclamacoes'
import { Route as AuthenticatedQrcodesRouteImport } from './routes/_authenticated/qrcodes'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedIntegracoesRouteImport } from './routes/_authenticated/integracoes'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedEmpresaRouteImport } from './routes/_authenticated/empresa'
import { Route as AuthenticatedDespesasRouteImport } from './routes/_authenticated/despesas'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedAvaliacoesRouteImport } from './routes/_authenticated/avaliacoes'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprimirRoute = ImprimirRouteImport.update({
  id: '/imprimir',
  path: '/imprimir',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroEmpresaRoute = CadastroEmpresaRouteImport.update({
  id: '/cadastro-empresa',
  path: '/cadastro-empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliarRoute = AvaliarRouteImport.update({
  id: '/avaliar',
  path: '/avaliar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReservasRoute = AuthenticatedReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReclamacoesRoute =
  AuthenticatedReclamacoesRouteImport.update({
    id: '/reclamacoes',
    path: '/reclamacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQrcodesRoute = AuthenticatedQrcodesRouteImport.update({
  id: '/qrcodes',
  path: '/qrcodes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegracoesRoute =
  AuthenticatedIntegracoesRouteImport.update({
    id: '/integracoes',
    path: '/integracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresaRoute = AuthenticatedEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDespesasRoute = AuthenticatedDespesasRouteImport.update({
  id: '/despesas',
  path: '/despesas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvaliacoesRoute = AuthenticatedAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avaliar': typeof AvaliarRoute
  '/cadastro-empresa': typeof CadastroEmpresaRoute
  '/imprimir': typeof ImprimirRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/qrcodes': typeof AuthenticatedQrcodesRoute
  '/reclamacoes': typeof AuthenticatedReclamacoesRoute
  '/reservas': typeof AuthenticatedReservasRoute
  '/vendas': typeof AuthenticatedVendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/avaliar': typeof AvaliarRoute
  '/cadastro-empresa': typeof CadastroEmpresaRoute
  '/imprimir': typeof ImprimirRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/despesas': typeof AuthenticatedDespesasRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/integracoes': typeof AuthenticatedIntegracoesRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/qrcodes': typeof AuthenticatedQrcodesRoute
  '/reclamacoes': typeof AuthenticatedReclamacoesRoute
  '/reservas': typeof AuthenticatedReservasRoute
  '/vendas': typeof AuthenticatedVendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/avaliar': typeof AvaliarRoute
  '/cadastro-empresa': typeof CadastroEmpresaRoute
  '/imprimir': typeof ImprimirRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/despesas': typeof AuthenticatedDespesasRoute
  '/_authenticated/empresa': typeof AuthenticatedEmpresaRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/integracoes': typeof AuthenticatedIntegracoesRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/qrcodes': typeof AuthenticatedQrcodesRoute
  '/_authenticated/reclamacoes': typeof AuthenticatedReclamacoesRoute
  '/_authenticated/reservas': typeof AuthenticatedReservasRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/avaliar'
    | '/cadastro-empresa'
    | '/imprimir'
    | '/sitemap.xml'
    | '/avaliacoes'
    | '/clientes'
    | '/despesas'
    | '/empresa'
    | '/equipe'
    | '/integracoes'
    | '/mapa'
    | '/painel'
    | '/qrcodes'
    | '/reclamacoes'
    | '/reservas'
    | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/avaliar'
    | '/cadastro-empresa'
    | '/imprimir'
    | '/sitemap.xml'
    | '/avaliacoes'
    | '/clientes'
    | '/despesas'
    | '/empresa'
    | '/equipe'
    | '/integracoes'
    | '/mapa'
    | '/painel'
    | '/qrcodes'
    | '/reclamacoes'
    | '/reservas'
    | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/avaliar'
    | '/cadastro-empresa'
    | '/imprimir'
    | '/sitemap.xml'
    | '/_authenticated/avaliacoes'
    | '/_authenticated/clientes'
    | '/_authenticated/despesas'
    | '/_authenticated/empresa'
    | '/_authenticated/equipe'
    | '/_authenticated/integracoes'
    | '/_authenticated/mapa'
    | '/_authenticated/painel'
    | '/_authenticated/qrcodes'
    | '/_authenticated/reclamacoes'
    | '/_authenticated/reservas'
    | '/_authenticated/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AvaliarRoute: typeof AvaliarRoute
  CadastroEmpresaRoute: typeof CadastroEmpresaRoute
  ImprimirRoute: typeof ImprimirRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprimir': {
      id: '/imprimir'
      path: '/imprimir'
      fullPath: '/imprimir'
      preLoaderRoute: typeof ImprimirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-empresa': {
      id: '/cadastro-empresa'
      path: '/cadastro-empresa'
      fullPath: '/cadastro-empresa'
      preLoaderRoute: typeof CadastroEmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliar': {
      id: '/avaliar'
      path: '/avaliar'
      fullPath: '/avaliar'
      preLoaderRoute: typeof AvaliarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservas': {
      id: '/_authenticated/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof AuthenticatedReservasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reclamacoes': {
      id: '/_authenticated/reclamacoes'
      path: '/reclamacoes'
      fullPath: '/reclamacoes'
      preLoaderRoute: typeof AuthenticatedReclamacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/qrcodes': {
      id: '/_authenticated/qrcodes'
      path: '/qrcodes'
      fullPath: '/qrcodes'
      preLoaderRoute: typeof AuthenticatedQrcodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integracoes': {
      id: '/_authenticated/integracoes'
      path: '/integracoes'
      fullPath: '/integracoes'
      preLoaderRoute: typeof AuthenticatedIntegracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa': {
      id: '/_authenticated/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AuthenticatedEmpresaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/despesas': {
      id: '/_authenticated/despesas'
      path: '/despesas'
      fullPath: '/despesas'
      preLoaderRoute: typeof AuthenticatedDespesasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avaliacoes': {
      id: '/_authenticated/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AuthenticatedAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAvaliacoesRoute: typeof AuthenticatedAvaliacoesRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedDespesasRoute: typeof AuthenticatedDespesasRoute
  AuthenticatedEmpresaRoute: typeof AuthenticatedEmpresaRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedIntegracoesRoute: typeof AuthenticatedIntegracoesRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedQrcodesRoute: typeof AuthenticatedQrcodesRoute
  AuthenticatedReclamacoesRoute: typeof AuthenticatedReclamacoesRoute
  AuthenticatedReservasRoute: typeof AuthenticatedReservasRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAvaliacoesRoute: AuthenticatedAvaliacoesRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedDespesasRoute: AuthenticatedDespesasRoute,
  AuthenticatedEmpresaRoute: AuthenticatedEmpresaRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedIntegracoesRoute: AuthenticatedIntegracoesRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedQrcodesRoute: AuthenticatedQrcodesRoute,
  AuthenticatedReclamacoesRoute: AuthenticatedReclamacoesRoute,
  AuthenticatedReservasRoute: AuthenticatedReservasRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AvaliarRoute: AvaliarRoute,
  CadastroEmpresaRoute: CadastroEmpresaRoute,
  ImprimirRoute: ImprimirRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
