import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Filter } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { useCurrentCompany } from "@/lib/data";
import { fmtBRL } from "@/lib/format";

const C={navy:"#173F52",blue:"#256A8A",sky:"#67A6BF",teal:"#0F766E",green:"#16A34A",revenue:"#15803D",red:"#C94A4A",grid:"#DDE6EA"};
const n=(v:any)=>Number(v||0); const today=()=>new Date().toISOString().slice(0,10); const add=(d:string,x:number)=>{const z=new Date(`${d}T12:00:00Z`);z.setUTCDate(z.getUTCDate()+x);return z.toISOString().slice(0,10)};
const dates=(a:string,b:string)=>{const out:string[]=[];for(let d=a;d<=b;d=add(d,1))out.push(d);return out}; const br=(d:string)=>new Date(`${d}T12:00:00`).toLocaleDateString("pt-BR",{day:"2-digit",month:"2-digit"});
const valid=(r:any)=>!String(r.status||"").toLowerCase().includes("cancel"); const overlap=(r:any,a:string,b:string)=>r.checkin<=b&&r.checkout>a;
const stayDays=(r:any,a:string,b:string)=>{const s=r.checkin>a?r.checkin:a,e=r.checkout<add(b,1)?r.checkout:add(b,1),o:string[]=[];for(let d=s;d<e;d=add(d,1))o.push(d);return o};
const pct=(v:number)=>`${v.toFixed(1).replace(".",",")}%`; const norm=(s:any)=>String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().trim();

type Source={reservations:any[];sales:any[];expenses:any[];rooms:any[];feedbacks:any[];forecast:any[]};

export function FilteredHotelExecutiveDashboard(){
 const company=useCurrentCompany(),companyId=company.data?.id,t=today();
 const [start,setStart]=useState(`${t.slice(0,7)}-01`),[end,setEnd]=useState(t),[channel,setChannel]=useState("Todos"),[open,setOpen]=useState(false);
 const q=useQuery({queryKey:["filtered-exec-v1",companyId],enabled:!!companyId,queryFn:async():Promise<Source>=>{const [r,s,e,rm,f,fc]=await Promise.all([
  (supabase as any).from("bi_reservas_decisao").select("*").eq("company_id",companyId).limit(10000),
  (supabase as any).from("sales").select("data,total,comprador_tipo,status,reserva_id,quarto").eq("company_id",companyId).limit(10000),
  (supabase as any).from("expenses").select("data,categoria,descricao,valor").eq("company_id",companyId).limit(10000),
  (supabase as any).from("rooms").select("numero,configuracao,preco,banheiro").eq("company_id",companyId).order("numero"),
  (supabase as any).from("feedbacks").select("quarto,hospede_nome,nota_geral,nota_externa_10,nota_limpeza,nota_conforto,nota_chuveiro,nota_banheiro,nota_cama,nota_silencio,nota_wifi,fonte_avaliacao,detalhes_externos,quarto_match_confidence,created_at").eq("company_id",companyId).limit(5000),
  supabase.functions.invoke("hotel-random-forest",{body:{company_id:companyId}})
 ]);for(const x of [r,s,e,rm,f])if(x.error)throw x.error;return{reservations:r.data||[],sales:s.data||[],expenses:e.data||[],rooms:(rm.data||[]).map((x:any)=>({...x,quarto:n(x.numero)})),feedbacks:f.data||[],forecast:fc.data?.occupancy?.forecast||[]}}});

 const m=useMemo(()=>{if(!q.data)return null;const d=q.data,roomCount=Math.max(1,d.rooms.length),rs=d.reservations.filter(r=>overlap(r,start,end)&&(channel==="Todos"||r.canal_analitico===channel)),ok=rs.filter(valid),ids=new Set(ok.map(r=>r.reserva_id));
  const ss=d.sales.filter(s=>s.data>=start&&s.data<=end&&!String(s.status||"").toLowerCase().includes("cancel")&&(channel==="Todos"||(s.reserva_id&&ids.has(s.reserva_id))));
  const map=new Map<string,{rooms:Set<number>,roomRevenue:number,products:number}>();for(const x of dates(start,end))map.set(x,{rooms:new Set(),roomRevenue:0,products:0});
  for(const r of ok){const ons=stayDays(r,start,end),full=Math.max(1,stayDays(r,r.checkin,add(r.checkout,-1)).length||n(r.diarias)||1),per=n(r.valor_total)/full;for(const x of ons){const z=map.get(x)!;if(r.quarto!=null)z.rooms.add(n(r.quarto));z.roomRevenue+=per;}}
  for(const s of ss){const z=map.get(s.data);if(z)z.products+=n(s.total)}
  const daily=[...map].map(([date,x])=>({date,label:br(date),ocupacao:x.rooms.size/roomCount*100,hospedagem:x.roomRevenue,produtos:x.products,total:x.roomRevenue+x.products}));
  const roomRevenue=daily.reduce((a,b)=>a+b.hospedagem,0),products=daily.reduce((a,b)=>a+b.produtos,0),revenue=roomRevenue+products,roomNights=daily.reduce((a,b)=>a+b.ocupacao*roomCount/100,0),available=roomCount*daily.length,occupancy=available?roomNights/available*100:0,adr=roomNights?roomRevenue/roomNights:0,revpar=available?roomRevenue/available:0,trevpar=available?revenue/available:0;
  const allOk=d.reservations.filter(r=>overlap(r,start,end)&&valid(r)),allIds=new Set(allOk.map(r=>r.reserva_id)),allSales=d.sales.filter(s=>s.data>=start&&s.data<=end&&!String(s.status||"").toLowerCase().includes("cancel")&&(s.reserva_id?allIds.has(s.reserva_id):true));
  const allRevenue=allOk.reduce((a,r)=>{const on=stayDays(r,start,end).length,full=Math.max(1,stayDays(r,r.checkin,add(r.checkout,-1)).length||n(r.diarias)||1);return a+n(r.valor_total)*on/full},0)+allSales.reduce((a,s)=>a+n(s.total),0),share=channel==="Todos"?1:(allRevenue?revenue/allRevenue:0);
  const expFull=d.expenses.filter(e=>e.data>=start&&e.data<=end).reduce((a,e)=>a+n(e.valor),0),recorded=expFull*share,daysN=daily.length,months=daysN/30.44,estimatedFull=allRevenue*.2+(4*1700+1900)*months+500*daysN/7+2050*months,estimated=estimatedFull*share,gop=revenue-recorded,goppar=available?gop/available:0;
  const sourceMap=new Map<string,number>();for(const r of ok){const on=stayDays(r,start,end).length,full=Math.max(1,stayDays(r,r.checkin,add(r.checkout,-1)).length||n(r.diarias)||1);sourceMap.set(r.canal_analitico,(sourceMap.get(r.canal_analitico)||0)+n(r.valor_total)*on/full)}if(products)sourceMap.set("Produtos",products);const sources=[...sourceMap].map(([name,value])=>({name,value}));
  const profiles=count(ok,(r:any)=>r.perfil_familiar||"Não informado"),ages=count(ok,(r:any)=>r.faixa_idade||"Não informado"),children=count(ok,(r:any)=>n(r.quantidade_filhos)<=0?"Sem filhos":n(r.quantidade_filhos)===1?"1 filho":"2+ filhos");
  const productSegments=["hospede","funcionario","empresa","outro"].map(k=>{const vals=ss.filter(s=>buyer(s.comprador_tipo)===k).map(s=>n(s.total)).filter(Boolean).sort((a,b)=>a-b);return{name:labelBuyer(k),compras:vals.length,total:vals.reduce((a,b)=>a+b,0),mediana:median(vals)}}).filter(x=>x.compras);
  const roomMetrics=d.rooms.map(room=>{const rr=ok.filter(r=>n(r.quarto)===room.quarto);let diarias=0,receita=0;for(const r of rr){const on=stayDays(r,start,end).length,full=Math.max(1,stayDays(r,r.checkin,add(r.checkout,-1)).length||n(r.diarias)||1);diarias+=on;receita+=n(r.valor_total)*on/full}const ff=d.feedbacks.filter(f=>f.quarto===room.quarto&&String(f.created_at).slice(0,10)>=start&&String(f.created_at).slice(0,10)<=end&&(f.quarto_match_confidence==null||n(f.quarto_match_confidence)>=.7)&&(channel==="Todos"||(norm(f.fonte_avaliacao).includes("booking")?channel==="Booking":true)));const notes=ff.map(score).filter((x:any)=>x!=null) as number[],cats=catScores(ff),best=[...cats].sort((a,b)=>b.avg-a.avg)[0],worst=[...cats].sort((a,b)=>a.avg-b.avg)[0];return{quarto:room.quarto,hospedagens:rr.length,diarias,receita,adr:diarias?receita/diarias:0,avaliacoes:notes.length,nota:notes.length?notes.reduce((a,b)=>a+b,0)/notes.length:null,destaque:best&&best.n?`${best.name} ${best.avg.toFixed(1).replace(".",",")}`:"—",atencao:worst&&worst.n?`${worst.name} ${worst.avg.toFixed(1).replace(".",",")}`:"—"}});
  const top=[...roomMetrics].sort((a,b)=>b.hospedagens-a.hospedagens||b.diarias-a.diarias).slice(0,10),low=[...roomMetrics].sort((a,b)=>a.hospedagens-b.hospedagens||a.diarias-b.diarias).slice(0,10);
  const baseShare=channel==="Todos"?1:(allOk.reduce((a,r)=>a+stayDays(r,start,end).length,0)?ok.reduce((a,r)=>a+stayDays(r,start,end).length,0)/allOk.reduce((a,r)=>a+stayDays(r,start,end).length,0):0),forecast=d.forecast.filter((f:any)=>f.date>t&&f.date<=end).map((f:any)=>({date:f.date,label:br(f.date),previsto:n(f.expected_occupancy)*baseShare}));
  const risk=rs.filter((r:any)=>r.elegivel_cancelamento_pre_checkin),cancel=risk.length?risk.reduce((a:any,r:any)=>a+n(r.cancelado_flag),0)/risk.length*100:0;
  return{daily,sources,profiles,ages,children,productSegments,top,low,revenue,occupancy,adr,revpar,trevpar,goppar,recorded,estimated,gop,forecast,cancel,risk:risk.length,allocated:channel!=="Todos"};
 },[q.data,start,end,channel,t]);
 if(q.isLoading||company.isLoading)return<div className="p-6 text-sm text-muted-foreground">Carregando painel...</div>;if(q.error||!m)return<div className="p-6 text-sm text-muted-foreground">Não foi possível carregar o painel.</div>;
 return <main className="space-y-3 px-2 pb-8 sm:px-3">
  <header className="relative flex items-center justify-between rounded-2xl border bg-card p-3"><h1 className="text-xl font-black text-pine-dark">Pulso do Hotel</h1><button onClick={()=>setOpen(!open)} className="inline-flex items-center gap-2 rounded-full border px-3 py-2 text-xs font-bold"><Filter className="h-4 w-4"/>Filtros</button>{open&&<div className="absolute right-3 top-14 z-20 grid w-[min(92vw,340px)] grid-cols-2 gap-2 rounded-2xl border bg-card p-3 shadow-xl"><input className="field" type="date" value={start} onChange={e=>setStart(e.target.value)}/><input className="field" type="date" value={end} onChange={e=>setEnd(e.target.value)}/><select className="field col-span-2" value={channel} onChange={e=>setChannel(e.target.value)}>{["Todos","Booking","WhatsApp","Direto / Recepção"].map(x=><option key={x}>{x}</option>)}</select></div>}</header>
  <section className="grid grid-cols-2 gap-2 md:grid-cols-3 xl:grid-cols-6">{[["Receita",fmtBRL(m.revenue)],["Ocupação",pct(m.occupancy)],["ADR",fmtBRL(m.adr)],["RevPAR",fmtBRL(m.revpar)],["TRevPAR",fmtBRL(m.trevpar)],[m.allocated?"GOPPAR rateado":"GOPPAR",fmtBRL(m.goppar)]].map(([a,b])=><Card key={a} title={a} value={b}/>)}</section>
  <section className="grid gap-3 xl:grid-cols-2"><Chart title="Receita por dia"><ResponsiveContainer width="100%" height={260}><BarChart data={m.daily}><CartesianGrid stroke={C.grid}/><XAxis dataKey="label"/><YAxis/><Tooltip formatter={(v:any)=>fmtBRL(n(v))}/><Legend/><Bar dataKey="hospedagem" name="Hospedagem" stackId="a" fill={C.revenue}/><Bar dataKey="produtos" name="Produtos" stackId="a" fill={C.teal}/></BarChart></ResponsiveContainer></Chart><Chart title="De onde vem a receita"><ResponsiveContainer width="100%" height={260}><BarChart data={m.sources} layout="vertical"><XAxis type="number"/><YAxis type="category" dataKey="name" width={120}/><Tooltip formatter={(v:any)=>fmtBRL(n(v))}/><Bar dataKey="value" fill={C.green}/></BarChart></ResponsiveContainer></Chart></section>
  <section className="grid gap-3 xl:grid-cols-2"><Chart title="Ocupação real e previsão"><ResponsiveContainer width="100%" height={260}><LineChart data={[...m.daily.map((x:any)=>({label:x.label,real:x.ocupacao})),...m.forecast]}><CartesianGrid stroke={C.grid}/><XAxis dataKey="label"/><YAxis domain={[0,100]}/><Tooltip/><Legend/><Line dataKey="real" name="Real" stroke={C.navy} strokeWidth={3}/><Line dataKey="previsto" name={channel==="Todos"?"Previsto":"Previsto estimado do canal"} stroke={C.sky} strokeWidth={3}/></LineChart></ResponsiveContainer></Chart><Chart title="Resultado operacional"><div className="grid grid-cols-2 gap-2 sm:grid-cols-3"><Mini t="Receita" v={fmtBRL(m.revenue)}/><Mini t={m.allocated?"Despesas rateadas":"Despesas registradas"} v={fmtBRL(m.recorded)}/><Mini t="GOP" v={fmtBRL(m.gop)}/><Mini t={m.allocated?"Custos estimados rateados":"Custos estimados"} v={fmtBRL(m.estimated)}/><Mini t="Cancelamento antecipado" v={`${pct(m.cancel)} · ${m.risk}`}/></div></Chart></section>
  <section className="grid gap-3 xl:grid-cols-3"><Chart title="Perfil dos hóspedes"><Bars rows={m.profiles}/></Chart><Chart title="Faixa etária"><Bars rows={m.ages}/></Chart><Chart title="Filhos"><Bars rows={m.children}/></Chart></section>
  <section className="grid gap-3 xl:grid-cols-2"><Chart title="Gasto com produtos por comprador"><table className="w-full text-xs"><tbody>{m.productSegments.map((x:any)=><tr className="border-b" key={x.name}><td className="py-2 font-bold">{x.name}</td><td>{x.compras} compras</td><td>{fmtBRL(x.total)}</td><td>Mediana {fmtBRL(x.mediana)}</td></tr>)}</tbody></table></Chart><Chart title="Custos"><p className="text-xs text-muted-foreground">Aluguel estimado em 20% da receita, salários 4 × R$ 1.700 + 1 × R$ 1.900, folguistas R$ 500/semana e padaria R$ 2.050/mês. Quando o canal é filtrado, custos sem canal são rateados pela participação na receita.</p></Chart></section>
  <section className="grid gap-3 xl:grid-cols-2"><Rooms title="Quartos com mais hospedagens" rows={m.top}/><Rooms title="Quartos com pouco ou nenhum uso" rows={m.low}/></section>
 </main>
}
function Card({title,value}:{title:string;value:string}){const revenue=title==="Receita";return<div className={`rounded-2xl border bg-card p-3 ${revenue?"border-green-600/35":""}`}><div className={`text-[10px] font-black uppercase ${revenue?"text-green-700":"text-muted-foreground"}`}>{title}</div><div className={`mt-1 text-lg font-black ${revenue?"text-green-700":""}`}>{value}</div></div>}
function Chart({title,children}:{title:string;children:any}){return<section className="rounded-2xl border bg-card p-3"><h2 className="mb-2 text-sm font-black text-primary">{title}</h2>{children}</section>}
function Mini({t,v}:{t:string;v:string}){const revenue=t==="Receita";return<div className={`rounded-xl border p-3 ${revenue?"border-green-600/35 bg-green-50/40":""}`}><div className={`text-[10px] font-bold uppercase ${revenue?"text-green-700":"text-muted-foreground"}`}>{t}</div><div className={`mt-1 font-black ${revenue?"text-green-700":""}`}>{v}</div></div>}
function Bars({rows}:{rows:any[]}){return<ResponsiveContainer width="100%" height={220}><BarChart data={rows} layout="vertical"><XAxis type="number"/><YAxis type="category" dataKey="name" width={120}/><Bar dataKey="value" fill={C.blue}/></BarChart></ResponsiveContainer>}
function Rooms({title,rows}:{title:string;rows:any[]}){return<section className="rounded-2xl border bg-card p-3"><h2 className="mb-2 text-sm font-black text-primary">{title}</h2><div className="overflow-x-auto"><table className="w-full text-xs"><thead><tr className="border-b text-left text-muted-foreground"><th>Quarto</th><th>Hospedagens</th><th>Diárias</th><th>Receita no período</th><th>ADR</th><th>Avaliação</th><th>Destaque</th><th>Atenção</th></tr></thead><tbody>{rows.map(r=><tr key={r.quarto} className="border-b"><td className="py-2 font-black">{r.quarto}</td><td>{r.hospedagens}</td><td>{r.diarias}</td><td className="font-bold text-green-700">{fmtBRL(r.receita)}</td><td>{fmtBRL(r.adr)}</td><td>{r.avaliacoes&&r.nota!=null?`${r.nota.toFixed(1).replace(".",",")} (${r.avaliacoes})`:"—"}</td><td>{r.destaque}</td><td>{r.atencao}</td></tr>)}</tbody></table></div></section>}
function count(rows:any[],fn:(x:any)=>string){const m=new Map<string,number>();for(const r of rows){const k=fn(r);m.set(k,(m.get(k)||0)+1)}return[...m].map(([name,value])=>({name,value})).sort((a,b)=>b.value-a.value)}
function buyer(v:any){const x=norm(v);return x.includes("hosp")?"hospede":x.includes("func")?"funcionario":x.includes("empresa")?"empresa":"outro"}function labelBuyer(v:string){return v==="hospede"?"Hóspedes":v==="funcionario"?"Funcionários":v==="empresa"?"Empresas":"Outros"}
function median(v:number[]){if(!v.length)return 0;const i=Math.floor(v.length/2);return v.length%2?v[i]:(v[i-1]+v[i])/2}
function score(f:any){return f.nota_externa_10!=null?n(f.nota_externa_10):f.nota_geral!=null?n(f.nota_geral)*2:null}
function catScores(fs:any[]){const defs=[['Limpeza',(f:any)=>detail(f,'limpeza')??five(f.nota_limpeza)],['Conforto',(f:any)=>detail(f,'conforto')??five(f.nota_conforto)],['Chuveiro',(f:any)=>five(f.nota_chuveiro)],['Banheiro',(f:any)=>five(f.nota_banheiro)],['Cama',(f:any)=>five(f.nota_cama)],['Silêncio',(f:any)=>five(f.nota_silencio)],['Wi-Fi',(f:any)=>five(f.nota_wifi)]] as any[];return defs.map(([name,get])=>{const v=fs.map(get).filter((x:any)=>x!=null);return{name,n:v.length,avg:v.length?v.reduce((a:number,b:number)=>a+b,0)/v.length:0}})}function detail(f:any,k:string){return f.detalhes_externos?.[k]==null?null:n(f.detalhes_externos[k])}function five(v:any){return v==null?null:n(v)*2}
